---
abstract: 'Upgrade existing prerequisites in place'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.006'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.008, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Prereqs-Upgrade
provides:
  Dist::Zilla::Plugin::Prereqs::Upgrade:
    file: lib/Dist/Zilla/Plugin/Prereqs/Upgrade.pm
    version: '0.001001'
recommends:
  Moose: '2.1204'
requires:
  Dist::Zilla::Role::PrereqSource: '0'
  Dist::Zilla::Util::ConfigDumper: '0'
  Moose: '0'
  Scalar::Util: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentnl/Dist-Zilla-Plugin-Prereqs-Upgrade/issues
  homepage: https://github.com/kentnl/Dist-Zilla-Plugin-Prereqs-Upgrade
  repository: https://github.com/kentnl/Dist-Zilla-Plugin-Prereqs-Upgrade.git
version: '0.001001'
x_BuiltWith:
  external_file: misc/built_with.json
x_Dist_Zilla:
  perl:
    version: '5.025010'
  plugins:
    -
      class: Dist::Zilla::Plugin::Bootstrap::lib
      config:
        Dist::Zilla::Role::Bootstrap:
          $Dist::Zilla::Role::Bootstrap::VERSION: '1.001003'
          distname: Dist-Zilla-Plugin-Prereqs-Upgrade
          fallback: '1'
          try_built: ~
          try_built_method: mtime
      name: Bootstrap::lib
      version: '1.001000'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: '0.54'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '6.008'
          include_underscores: 0
        Dist::Zilla::Role::MetaProvider::Provider:
          $Dist::Zilla::Role::MetaProvider::Provider::VERSION: '2.002004'
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
        Dist::Zilla::Role::ModuleMetadata:
          Module::Metadata: '1.000033'
          version: '0.004'
      name: '@Author::KENTNL/MetaProvides::Package'
      version: '2.004002'
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          $Module::Metadata::VERSION: '1.000033'
          _stash_key: x_BuiltWith
          external_file_name: misc/built_with.json
          show_config: '1'
          show_uname: '1'
          uname:
            uname_args:
              - -s
              - -o
              - -r
              - -m
              - -i
            uname_call: uname
          use_external_file: only
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: '1.004004'
    -
      class: Dist::Zilla::Plugin::Git::Contributors
      config:
        Dist::Zilla::Plugin::Git::Contributors:
          'git --version': 2.11.1
          include_authors: 0
          include_releaser: 0
          order_by: name
          paths: []
      name: '@Author::KENTNL/Git::Contributors'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::GatherDir:
          exclude_filename:
            - LICENSE
            - README
            - README.mkdn
            - README.pod
          exclude_match: []
          follow_symlinks: 0
          include_dotfiles: 1
          prefix: ''
          prune_directory: []
          root: .
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: 0
      name: '@Author::KENTNL/Git::GatherDir'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Author::KENTNL::TravisCI
      config:
        Dist::Zilla::Plugin::Author::KENTNL::TravisCI:
          fail_perls:
            - '5.8'
          skip_perls: []
      name: '@Author::KENTNL/Author::KENTNL::TravisCI'
      version: '0.001003'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::KENTNL/CopyXBuild'
      version: '0.163040'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::KENTNL/Test::ReportPrereqs'
      version: '0.025'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      config:
        Dist::Zilla::Plugin::Test::Kwalitee:
          filename: xt/release/kwalitee.t
          skiptest: []
      name: '@Author::KENTNL/Test::Kwalitee'
      version: '2.12'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      config:
        Dist::Zilla::Plugin::Test::EOL:
          filename: xt/author/eol.t
          finder:
            - ':ExecFiles'
            - ':InstallModules'
            - ':TestFiles'
          trailing_whitespace: 1
      name: '@Author::KENTNL/Test::EOL'
      version: '0.19'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: '2.000007'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/Test::Compile::PerFile/AUTOVIV/:InstallModulesPM'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Test::Compile::PerFile
      config:
        Dist::Zilla::Plugin::Test::Compile::PerFile:
          file:
            - lib/Dist/Zilla/Plugin/Prereqs/Upgrade.pm
          path_translator: base64_filter
          prefix: t/00-compile
          skip: []
          test_template: 02-raw-require.t.tpl
          xt_mode: ~
      name: '@Author::KENTNL/Test::Compile::PerFile'
      version: '0.003902'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: '3.000'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::RewriteVersion::Sanitized
      config:
        Dist::Zilla::Plugin::RewriteVersion:
          add_tarball_name: 0
          finders:
            - ':ExecFiles'
            - ':InstallModules'
          global: 0
          skip_version_provider: 0
        Dist::Zilla::Role::Version::Sanitize:
          $Dist::Zilla::Role::Version::Sanitize::VERSION: '0.002002'
          mantissa: '6'
          normal_form: numify
      name: '@Author::KENTNL/RewriteVersion::Sanitized'
      version: '0.001005'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.015'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.015'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: -SingleEncoding
              version: '4.015'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.015'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.015'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.015'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_ATTRIBUTES
              version: '4.015'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_METHODS
              version: '4.015'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.015'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.015'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.015'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.015'
      name: '@Author::KENTNL/PodWeaver'
      version: '4.008'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/BundleDevelSuggests'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Prereqs::AuthorDeps
      name: '@Author::KENTNL/Prereqs::AuthorDeps'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::KENTNL/MinimumPerl'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: '1.009'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/MakeMaker'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Author::KENTNL::RecommendFixes
      name: '@Author::KENTNL/Author::KENTNL::RecommendFixes'
      version: '0.005002'
    -
      class: Dist::Zilla::Plugin::Readme::Brief
      name: '@Author::KENTNL/ShippedReadme'
      version: '0.003000'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      config:
        Dist::Zilla::Role::FileWatcher:
          version: '0.006'
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: '0.163250'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      config:
        Dist::Zilla::Plugin::Test::CPAN::Changes:
          changelog: Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: '0.012'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: '10'
      name: '@Author::KENTNL/RunExtraTests'
      version: '0.029'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.1
          repo_root: .
      name: '@Author::KENTNL/Git::Check'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.1
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::KENTNL/commit_dirty_files'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          changelog: Changes
          signed: 0
          tag: 0.001001-source
          tag_format: '%v-source'
          tag_message: v%v
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.1
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::KENTNL/tag_master'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::Git::NextRelease
      name: '@Author::KENTNL/Git::NextRelease'
      version: '0.004000'
    -
      class: Dist::Zilla::Plugin::BumpVersionAfterRelease
      config:
        Dist::Zilla::Plugin::BumpVersionAfterRelease:
          finders:
            - ':ExecFiles'
            - ':InstallModules'
          global: 0
          munge_makefile_pl: 1
      name: '@Author::KENTNL/BumpVersionAfterRelease'
      version: '0.015'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - Changes
            - dist.ini
          allow_dirty_match:
            - (?^u:^lib/)
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.1
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::KENTNL/commit_release_changes'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: builds
          build_root: ~
          message: 'Build results of %h (on %b)'
          multiple_inheritance: 0
          release_branch: releases
          release_message: 'Build results of %h (on %b)'
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.1
          repo_root: .
      name: '@Author::KENTNL/Git::CommitBuild'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: releases
          changelog: Changes
          signed: 0
          tag: '0.001001'
          tag_format: '%v'
          tag_message: v%v
        Dist::Zilla::Role::Git::Repo:
          'git --version': 2.11.1
          repo_root: .
        Dist::Zilla::Role::Git::StringFormatter:
          time_zone: local
      name: '@Author::KENTNL/tag_release'
      version: '2.041'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: '0.026'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/::Role::BundleDeps'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::Prereqs::Upgrade
      config:
        Dist::Zilla::Plugin::Prereqs::Upgrade:
          modules:
            ExtUtils::MakeMaker: '7.0'
            Moose: '2.1204'
            Path::Tiny: '0.58'
            Test::More: '0.99'
      name: Prereqs::Upgrade
      version: '0.001001'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExtraTestFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':PerlExecFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '6.008'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '6.008'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '6.008'
x_authority: cpan:KENTNL
x_serialization_backend: 'YAML::Tiny version 1.70'
